### ISSUE TITLE
re-check bcdb instance usage

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#24]
After running the bcdb tests, which use `test` instance, the `system` instance of bcdb contains these tests' data.

**Comment by serboctor** [comment]
After finally getting the tests to work, I don't see anything suspicious in the `system` instance. There are no tests data when I called `system.get_all()`. There are only some clients and servers instances, some of which were indeed used in the tests, but that's normal because clients and servers instances are created in `system` by default.
