### ISSUE TITLE
autocomplete in shell does not work when names have . inside [development_fixes_autocomplete]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#289]
![image](https://user-images.githubusercontent.com/6021844/69529505-b1163d80-0f70-11ea-87a6-08fb3be8d2e2.png)

in our shell the .'s need to be replaced to e.g. !! so codecompletion can work

not sure "!!" works, something which works and we need to be able to go back to the real name

**Comment by xmonader** [comment]
I think can be easily fixed if we replace `.` with `__`  ? as a convention for fully qualified names?

**Comment by abom** [comment]
Trying to replace `.` would work, but IMHO, names should only be valid python identifier, they are being accessed as a property.

**Comment by despiegk** [comment]
ok to raise error if . inside

**Comment by xmonader** [comment]
let's have the packages with $3botauthor__$packagename instead of $3botauthor.$packagename so it can be a valid python identifier

**Comment by abom** [comment]
@xmonader We already use `.` in many places including schema URLs, trying to spot what's need to be changed.

**Comment by abom** [comment]
Branch: `development_fixes` in both core and threebot.

I added a check to raise an error if the instance name is not a valid python identifier here https://github.com/threefoldtech/jumpscaleX_core/commit/be873533a41f2f1cc78075482be0e6b3620c4aeb.

Also, i changed instance names of the packages to use `__` instead of `.` here https://github.com/threefoldtech/jumpscaleX_core/commit/af5bf44e531546fe0496038d6b34786ae56e96e5, still the other convention of dot separated names is used in gedis actors and schema urls, but for instance names, dot is not allowed anymore.

For current running servers, you need to make a list of installed packages, then remove all packages (with dot separated names), then restart the server and install your packages again, or clear bcdb (if no important data is there).

For now to get the full name of the package (dot separated), you can just call `package.fullname`.

Now auto-completions works normally:

![Screenshot from 2019-12-12 15-59-06](https://user-images.githubusercontent.com/511438/70718137-56af0800-1cf8-11ea-9874-63e04ff4588b.png)

**Comment by abom** [comment]
As a result, i'm now fixing webinterface package to use the right package name instead of the dot-separated names.

**Comment by xmonader** [comment]
please continue on branch development_fixes_autocomplete

**Comment by abom** [comment]
Fixed wiki and chat handlers at https://github.com/threefoldtech/jumpscaleX_threebot/commit/6567778574c4bfcdac0f4eebad3234ea62435d76.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
