### ISSUE TITLE
ZDB improvements & bug fix [development_zdb]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#290]
## todo

- [ ] coordinate with maxux that we have the repair & check tools back on ZDB
- [ ] integrate the tools in JSX ZDB server instance so we can test & verify a ZDB

**Comment by maxux** [comment]
It would be cool to have a call all together to sync with how zdb works internally.
Debug and dump tools are working, but repairing tools have to be finished, they haven't been updated since we have `libzdb`, which simplify lot of things but need some rewrite.

I don't see real issue with testnet explorer namespace (at least `tf_workloads` namespace) :/

**Comment by despiegk** [comment]
lets do the sync together

**Comment by despiegk** [comment]
moved to https://github.com/threefoldtech/home/issues/462
