### ISSUE TITLE
export/import for BCDB [development_fixes2]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#295]
- make sure export/import works well
- [Test](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/data/bcdb/tests/10_export.py)
- [Docs](https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/BCDB#exportimport)

**Comment by serboctor** [comment]
@despiegk do we want to export to a clean database? or also support exporting to a database with existing data and update data accordingly?

**Comment by serboctor** [comment]
@despiegk One solution would be to disregard ids change, and anywhere we want to create relationships between objects, we depend on the `name` since name is supposed to be unique. Would you be ok with that?

**Comment by despiegk** [comment]
no, because not every object has a name

**Comment by despiegk** [comment]
and id's are way more efficient to make the link between objects

**Comment by despiegk** [comment]
and we need auto increment (-: for BCDB functionality

**Comment by serboctor** [comment]
We only use relationships in ACLS and they have names. And we can clearly state in our docs that if you want to create a relationship, it should be done through the name. I don't see how sustaining the IDs can be doable using sequential zdb. Do you have have other solutions? @despiegk

**Comment by serboctor** [comment]
@maxux Added the value of the next_id to the `nsinfo` of `zdb` so I can avoid creating dummy objects whens it's not needed which ended up messing up my ids even more https://github.com/threefoldtech/0-db/commit/3443ff433c95af996acde906e74ca925031229c6

I did some fixes, added tests, and adds docs here https://github.com/threefoldtech/jumpscaleX_core/commit/1580f9d35bb79bb405791e4c33c5a61dedd2e66f

@despiegk the tests work fine now, and simple scenarios work fine. But like I said, due to the zdb autoincrementing on any update, then the export/import is guaranteed to work only when all models are loaded in the bcdb instance before being used. If models are loaded later on, this will mess up the ids when we try to export.

**Comment by serboctor** [comment]
I thought of an idea that might bypass the zdb issue, trying it and if it works will update the code and tests.

**Comment by serboctor** [comment]
This change helps avoid the zdb increment issue https://github.com/threefoldtech/jumpscaleX_core/commit/43240972b81bf74e13bd3617ab65be4caaf8eff7

**Comment by despiegk** [comment]
kristof needs to review

**Comment by john-kheir** [comment]
@despiegk Did u review?

**Comment by Pishoy** [comment]
verified 
 - jsx version
```
3BOTDEVEL:3bot:jumpscaleX_core: git log -1
commit d84625c72215807b788425d35d68a8eb840dd228 (HEAD -> development_fixes2, origin/development_fixes2)
Author: andrewayoub <andrew.a.mikhaeel@gmail.com>
Date:   Tue Dec 24 13:03:17 2019 +0200

    set empty value directly into datastor instead of creating gap object #295
```
