### ISSUE TITLE
test installers

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#3]
- [x] OSX
- [x] digital ocean
- [x] ubuntu 1804 natively 
- [x] container install

**Comment by waleedhammam** [comment]
In system:
- Interactive Installation: **Works OK**
- no-interactive installation: **Works OK**

Container:
- Interactive Installer: **Works OK**
-  no-interactive: Still asks for ssh-key

On macOS: **Works OK**

**Comment by waleedhammam** [comment]
It doesn't work now, gives this error
```
Tue 27 08:21:37 /tmp/InstallTools.py -1986 - execute                            : EXCEPTION: 
    cannot retry in interactive mode yet
```

**Comment by waleedhammam** [comment]
> It doesn't work now, gives this error
> 
> ```
> Tue 27 08:21:37 /tmp/InstallTools.py -1986 - execute                            : EXCEPTION: 
>     cannot retry in interactive mode yet
> ```

fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/b5c80f13684a66c71aa02f390f5965a12a1515fb

**current status**

In system:
Interactive Installation: **Works OK**
no-interactive installation: **Works OK**

Container:
Interactive Installer: **Works OK**
no-interactive: Asks a question for a key even it's no-interactive

On macOS: **Works OK**

**Comment by hossnys** [comment]
verified and here is the current status of installer :
current status

ubuntu 18.04
In system:
Interactive Installation: **Works OK**
no-interactive installation: **Works OK**

Container:
Interactive Installer: **Works OK**
no-interactive: Asks a question for a key even it's no-interactive; fixed with --no-sshagent
also there is an issue logged for this  here  https://github.com/threefoldtech/jumpscaleX_core/issues/53

On macOS: **Works OK**
