### ISSUE TITLE
[GEDIS] Server should send all schemas used in the loaded actors to the client

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_core#322]
In order to make the client able to read and send serialized content to the server, The client should load all the schemas used in all the actors loaded.

currently `jsx_schemas_get` returns system schemas only, this should also contains all schemas used

**Comment by ranatrk** [comment]
The schemas are sent to the client in the return of `api_meta_get`. Tested using gedis client on a different machine than the server where the actors can be accessed successfully. 
**The issue** arises when trying the to access them from the explorer server due to different schemas available. Currently looking into that.

**Comment by ranatrk** [comment]
Tried to reproduce the issue on different machine, including changing in the schema then reloading from the client but couldn't reproduce.
The issue arises when doing the following by connecting to gedis server of explorer node:
```
client = j.clients.gedis.get(name="explorer", port=8901, host="explorer.testnet.grid.tf")
client.actors.farms.list()
```
but works with the following:
```
client.actors.farms.list()
```

**Comment by despiegk** [comment]
@andrewayoub currently jsx_schemas_get returns system schemas only, this should also contains all schemas used is that the case?
