### ISSUE TITLE
Inconsistent data shown with actor_all

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#406]
![image](https://user-images.githubusercontent.com/64129/71994747-fc935b00-3241-11ea-9f69-318ed548f6e4.png)

![image](https://user-images.githubusercontent.com/64129/71994731-f69d7a00-3241-11ea-85ec-f57decc0c4d0.png)

**Comment by serboctor** [comment]
@xmonader I checked JSBase.py and it seems if an object has over 20 properties, it doesn't display the properties, which I guess makes sense otherwise you end up with tons of data in the string representation. `actors_all` has over 40 proprty, I locally changed the limit to 50, and it works fine then, but I guess we want to keep the limit the way it is, no?
![Screenshot from 2020-01-09 18-55-28](https://user-images.githubusercontent.com/6323012/72088052-1ef4a980-3312-11ea-95ad-01d02a54f142.png)

**Comment by xmonader** [comment]
Fixed in f84ee11bf19149f2f473bd10dc57877f16e11cf4

![image](https://user-images.githubusercontent.com/64129/72216834-057c7900-352f-11ea-868f-3d3b55d84ef1.png)

![image](https://user-images.githubusercontent.com/64129/72216841-1200d180-352f-11ea-8103-24a136a76bba.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified
