### ISSUE TITLE
comparing str to an enum doesn't work properly 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#429]
![image](https://user-images.githubusercontent.com/64129/72355912-00ffbe00-36f1-11ea-8e6a-fcead8b8c5aa.png)

this was required to fix the comparison, but this means it might be broken in other code

https://github.com/threefoldtech/jumpscaleX_threebot/blob/489ce1ec0ab36a1f3e24835559ef0d0bb4266694/ThreeBotPackages/zerobot/packagemanager/actors/package_manager.py#L181

**Comment by andrewayoub** [comment]
Enums currently are being compared by their value which can differ in different schemas depending on the order in the options list.

in the mentioned case the enum definition in the package schema is 
```
status = "init,config,toinstall,installed,tostart,disabled,error" (E)
```
and in schema_in for the actor
```
status = "all,init,config,toinstall,installed,tostart,disabled,error" (E)
```
**notice that a new option (all) added in the schema in**
so for example the value for "init" is (1) in the first schema and (2) in the other one 


## Suggested solution
in `__eq__` method in Enum objects we can compare by the string representation of the enum instead of the value 
![image](https://user-images.githubusercontent.com/5163693/72362012-17127c00-36fb-11ea-9387-892812046fc2.png)

is this an acceptable solution ?

**Comment by despiegk** [comment]
yes, string comparison ok

**Comment by andrewayoub** [comment]
fixed and added tests for enums here 
https://github.com/threefoldtech/jumpscaleX_core/blob/c9cd338fb111674c9aba97b078f58bd8ebc266c9/JumpscaleCore/data/schema/tests/13_enums.py

**Comment by Dinaamagdy** [comment]
verified on development run the enums tests and worked successfully 
![image](https://user-images.githubusercontent.com/24386802/72517578-51dff580-385c-11ea-9fcc-3139cfbdba07.png)
