### ISSUE TITLE
lapis server doesn't work when starting threebot server  [development_fixes103]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#479]
## Steps
start threebot server
j.servers.threebot.get().start(background=True)

## Issue  
check lapis process , will not find it but will find openresty port exist when u kill it and start threebot server again lapis will start correctly

**Comment by andrewayoub** [comment]
on starting threebot server it was checking if lapis is listening on port 80 or not, if it's listening it wasn't starting it, but if you didn't close lapis gracefuly, another process will be still running and will be listening on port 80, that's why it's safer to start lapis again each time

code :
https://github.com/threefoldtech/jumpscaleX_core/pull/480

**Comment by Dinaamagdy** [comment]
verified on development branch
