### ISSUE TITLE
SAL.FS: copyDirTree with deleting before copying.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#74]
### Steps:
1- Create a directory `test_dir`.
2- Create a file `test_file` inside `test_dir`.
3- Create a sub directory `subdir` under `test_dir`.
4- Create a file `file` insdie `subdir`.
5- Create a directory `test_dir2`.
6- Create a file `test_file2`.
7- Create a sub directory `subdir2` under `test_dir2`.
8- Create a file `file2` insdie `subdir2`.
5- Copy this `test_dir` to `test_dir2` with deletefirst=True.
```
j.sal.fs.copyDirTree("/tmp/test_dir", "/tmp/test_dir2", keepsymlinks=True, deletefirst=True, rsync=False, overwriteFiles=True)
```
### Expected Result:
Find only the content of `test_dir`.
### Actual Result:
```
ls test_dir2
subdir  subdir2  test_file  test_file2
```

**Comment by serboctor** [comment]
I checked the implementation, and apparently, `deletefirst` deletes files and directories on the destination that exists (has the same name) on the source too, but if a file/dir doesn't exist on src, it won't delete it from the destination. so if you create directories with the same name, for example, on both src and destination, and you do the call with `deletefirst=True`, you'll end up with the directory from the src instead of a merge of their contents. 
example:
if your have this source:
```
tree test_dir
test_dir
├── subdir
└── test_file
```
and this destination:
```
test_dir2
├── subdir
│   └── file
├── subdir2
│   └── file2
├── test_file
└── test_file2
```

and you call 
```j.sal.fs.copyDirTree("/tmp/test_dir", "/tmp/test_dir2", keepsymlinks=True, deletefirst=True, rsync=False, overwriteFiles=True)```

you'll end up with:
```
 test_dir2
├── subdir
├── subdir2
│   └── file2
├── test_file
└── test_file2
```

instead of : 
```
test_dir2
├── subdir
│   └── file
├── subdir2
│   └── file2
├── test_file
└── test_file2
```

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/516130da991bc50e25af23bc715031bb53d83ed2
