### ISSUE TITLE
system fs hash test failing

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#91]
`j.sal.fs.test('hash')` is failing on dir and file md5 checksums

**Comment by zgorizzo69** [comment]
@waleedhammam can you give more details about this commit ?
https://github.com/threefoldtech/jumpscaleX_core/commit/dbb4ee4ae1d60320feb075e16968474920c7906f. What was the problem with the existing code ?
now a folder hash is equal to the hash of the file inside the folder. Is it now the required behaviour ?

**Comment by zgorizzo69** [comment]
@waleedhammam  plus the function md5sum does exactly what you have raplace 
I will revert this as we don't want to repeat ourselves (fyi i am on the satbilize branch)

**Comment by waleedhammam** [comment]
@zgorizzo69 The existing code was updating the dir hash with only the md5 of files "the string itself".
What we need is to update md5 with the content of the files themselves.
So if u have a directory, copied to to another place won't be the same dir md5 and this is wrong.
Fixed it by splitting files into chunks update the hash with each chunk. You can test it

**Comment by zgorizzo69** [comment]
@waleedhammam I have revert and added the test to check that a folder keeps the same hash even if it is moved and the test passes so I don't understand your argument. Maybe you can verify/review the code and if necessary add more test ? I also have limited the md5sum function to only one file as anyway it couldn't run with a list of files because of the decorators

**Comment by waleedhammam** [comment]
@zgorizzo69 It turns out both algorithms are right. but the problem is in this line:
https://github.com/threefoldtech/jumpscaleX_core/blob/d7b15db3f24010e34b5d94dbffe424ecca179257/JumpscaleCore/sal/fs/SystemFS.py#L1388
`listSymlinks=True` and `followSymlinks=True`  should be = False. because whatever I try symlinks corrupt the test even with external libs like `checksumdir`. so we  should ignore symlinks.

**Comment by zgorizzo69** [comment]
ok cool maybe add that to the test

**Comment by waleedhammam** [comment]
> ok cool maybe add that to the test

added at https://github.com/threefoldtech/jumpscaleX_core/commit/13c45144fbe09fca9be717408a0d3a3891db6413
