### ISSUE TITLE
tmux server:  sessions_list, session_kill

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#93]
## Steps 
- create one session [j.servers.tmux.server.new_session(name)]
- kill this session [j.servers.tmux.server.kill_session(name)]
- get sessions list [.servers.tmux.server.list_sessions()]

## Error 
sessions_list raise error instead of return empty list
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 183, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 173, in _sessions
    return self._list_sessions()
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 153, in _list_sessions
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['no server running on /tmp/tmux-0/default']

['no server running on /tmp/tmux-0/default']
```

**Comment by serboctor** [comment]
`j.servers.tmux.server` is mostly meant for internal use. The `list_session` is from an imported library so we don't really have any control over it. However, there are some parts of the flow that aren't consistent, in the initialization of the server, it will raise an error if it finds more than 1 session, but later on, anyone can start more than one session using `j.servers.tmux.server.new_session`. Also, the first time you call `j.servers.tmux.server` it will create the session `main`, but later on, if you call it again after you kill the session, it won't create it again. 

I refactored the old flow to work as follows:
- Calling `j.servers.tmux.server` will always check if there is session main, and if there isn't, it will start a new session `main`. This means the `list_session` function will always return at least one session called `main`.
- Calling `j.servers.tmux.server` will not raise an error if other tmux sessions are running.
- `j.servers.tnux.session` will filter using name `main` instead of assuming there is one session running and using index 0.

https://github.com/threefoldtech/jumpscaleX_core/commit/c3b2b725badae14c7870aefbeddac82c7930f76c

**Comment by siddiquagig** [comment]
Verified:

```
JSX> j.servers.tmux.server.list_sessions()
[Session($0 jsx), Session($3 main)]

JSX> j.server.tmux.server.kill_session("main")
<libtmux.server.Server object at 0x7f31f0cb9a20>


we can see it restarted the main session:

JSX> j.servers.tmux.server.list_sessions()
[Session($0 jsx), Session($4 main)]
```
